# This is a basic workflow to help you get started with Actions

name: package

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          dd if=<(openssl enc -aes-256-ctr -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt < /dev/zero) of=filename bs=1M count=2100 iflag=fullblock
          zip package.1.0.0.zip filename

      - name: Push Package to Octopus Deploy
          # You may pin to the exact commit or the version.
          # uses: OctopusDeploy/push-package-action@035fb4fdbe77401574ec62275f9a531c570bd420
        uses: OctopusDeploy/push-package-action@v3.0.4
        with:
          # A multi-line list of packages to push to Octopus Deploy.
          packages: package.1.0.0.zip
          # Determines the action to perform with package if it already exists in the repository. Valid values are "FailIfExists", "OverwriteExisting", and "IgnoreIfExists".
          overwrite_mode: OverwriteExisting
          # The API key used to access Octopus Deploy. You must provide an API key or username and password. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended that this value retrieved from a GitHub secret.
          api_key: ${{ secrets.BENPEARCE_API_KEY }}
          # The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). It is recommended to retrieve this value from an environment variable.
          server: https://benpearce.testoctopus.app
          space: Default
