# This is a basic workflow to help you get started with Actions

name: package

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Octopus CLI
      # You may pin to the exact commit or the version.
      # uses: OctopusDeploy/install-octopus-cli-action@b44313a25eb0e47b3d726eb7a080e0c5de9186ed
        uses: OctopusDeploy/install-octopus-cli-action@v3.0.0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          dd if=<(openssl enc -aes-256-ctr -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt < /dev/zero) of=filename bs=1M count=2100 iflag=fullblock
          zip package.1.0.0.zip filename
      
      - name: push package
        env:
          OCTOPUS_URL: https://benpearce.testoctopus.app
          OCTOPUS_API_KEY: ${{ secrets.BENPEARCE_API_KEY }}
        run: |
          octopus package upload --space Default --package package.1.0.0.zip --no-prompt
          

      
