name: create-zip
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: | 
          mkdir work
          cd work
          echo "test output" > .dotfile
          cat .dotfile
          touch test.txt
          touch no-extension
        shell: bash
      - name: Create Zip Package for Octopus Deploy
      # You may pin to the exact commit or the version.
        uses: OctopusDeploy/create-zip-package-action@06107900912e6dc6be9a56f4340cd54a8024c61a
        #uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: output
          version: 1.0.0
          output_folder: ./pack
          base_path: .
          files: |
            work/**/*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./pack/*
      - name: Push Package to Octopus Deploy
          # You may pin to the exact commit or the version.
          # uses: OctopusDeploy/push-package-action@b74e803857cf8d3807862d2cb2228b1572ccfcbe
        uses: OctopusDeploy/push-package-action@91272d96d0464bce0f9b7bf61ab50bd6dae6b508
        with:
          # A multi-line list of packages to push to Octopus Deploy.
          packages: ./pack/output.1.0.0.zip
          api_key: API-XXX
          server: https://benpearce.testoctopus.app
          space: cli demo
