name: create-zip
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: | 
          echo "test output" > .dotfile
          ls -lah
          cat .dotfile
        shell: bash
      - name: Create Zip Package for Octopus Deploy
      # You may pin to the exact commit or the version.
      # uses: OctopusDeploy/create-zip-package-action@6d73e1f62030dfa23534ff0d279774177d5ea1ea
        #uses: OctopusDeploy/create-zip-package-action@ed00269bd60c1369b7b10e1b8d88edca0be12fc5
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: output
          version: 1.0.0
          output_folder: ./pack
          base_path: .
          files: |
            **/*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./pack/*
