name: create-zip
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: | 
          mkdir work
          cd work
          echo "test output" > .dotfile
          cat .dotfile
          touch test.txt
          touch no-extension
        shell: bash
      - name: Create Zip Package for Octopus Deploy
      # You may pin to the exact commit or the version.
        uses: OctopusDeploy/create-zip-package-action@06107900912e6dc6be9a56f4340cd54a8024c61a
        #uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: output
          version: 1.0.0
          output_folder: ./pack
          base_path: .
          files: |
            work/**/*.*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./pack/*
