# This is a basic workflow to help you get started with Actions

name: oidc-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      id-token: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Octopus CLI
      # You may pin to the exact commit or the version.
      # uses: OctopusDeploy/install-octopus-cli-action@b44313a25eb0e47b3d726eb7a080e0c5de9186ed
        uses: OctopusDeploy/install-octopus-cli-action@v3.0.0
      - name: Login to Octopus Deploy
  # You may pin to the exact commit or the version.
  # uses: OctopusDeploy/login@37c884ed5aeebec1e9bb35f0e860ae43cb946772
        uses: OctopusDeploy/login@v1.0.1
        with:
          server: https://walleye-equipped-mayfly.ngrok-free.app
      # The id of the service account when using OpenID Connect to login. It is strongly recommended that this value retrieved from a GitHub secret.
          service_account_id: 7bcca36c-830b-49d6-a5b2-5e9791acb591
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: octopus space list
